services:
  - type: web
    name: migradores
    env: node
    buildCommand: ./build.sh
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        value: postgresql://migrantes_ox59_user:W3Km6UrMiS3hokvEQ6xgXXsq2iEIayXD@dpg-d00pjbadbo4c73dilgeg-a/migrantes_ox59
      - key: PGHOST
        value: dpg-d00pjbadbo4c73dilgeg-a
      - key: PGPORT
        value: 5432
      - key: PGUSER
        value: migrantes_ox59_user
      - key: PGPASSWORD
        value: W3Km6UrMiS3hokvEQ6xgXXsq2iEIayXD
      - key: PGDATABASE
        value: migrantes_ox59
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        value: fO2pL9zX3qY7tV5wR1bN8mS6kI0dE4aG