-- Seed data para MigraGuía en español

-- Categorías de recursos
INSERT INTO resource_categories (id, name, icon, description) VALUES
(1, 'Procedimientos Legales', 'legal', 'Guías, formularios y requisitos para solicitudes de asilo, visados y permisos.'),
(2, 'Trabajo y Empleo', 'work', 'Portales de empleo, validación de títulos y derechos laborales para migrantes.'),
(3, 'Salud y Bienestar', 'health', 'Acceso a servicios sanitarios, apoyo psicológico y emergencias médicas.'),
(4, 'Educación', 'education', 'Información sobre escolarización, homologación de estudios y aprendizaje de idiomas.'),
(5, 'Vivienda', 'housing', 'Ayudas para alquiler, derechos de inquilinos y centros de acogida temporal.'),
(6, 'Derechos Humanos', 'rights', 'Información sobre tus derechos fundamentales como migrante o refugiado.');

-- Países
INSERT INTO countries (id, name, flag_url, image_url, description) VALUES
(1, 'España', 'https://images.unsplash.com/photo-1623777815243-65427924c10e?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1555990283-6fe8bfbec9bc?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80', 'España es uno de los países más acogedores de Europa para los migrantes, especialmente para aquellos que provienen de América Latina debido a los lazos culturales e idiomáticos. Aquí encontrarás información relevante sobre los distintos procesos migratorios, oportunidades laborales, acceso a servicios de salud, educación y vivienda.'),
(2, 'Colombia', 'https://images.unsplash.com/photo-1599413850737-5fd5ff448fb1?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1599413850737-5fd5ff448fb1?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80', 'Colombia se ha convertido en un importante país de acogida para migrantes, especialmente venezolanos. Su política migratoria ha evolucionado para responder a los desafíos recientes. Aquí encontrarás información sobre el Permiso Especial de Permanencia (PEP), acceso a servicios básicos y oportunidades de integración.'),
(3, 'Chile', 'https://images.unsplash.com/photo-1510253687831-9a0a16d2fafc?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1510253687831-9a0a16d2fafc?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80', 'Chile ha experimentado un aumento significativo en su población migrante en la última década. Su sistema migratorio ofrece diversas visas y permisos de residencia. Aquí encontrarás información sobre los requisitos, procesos de regularización y acceso a servicios de salud, educación y empleo.'),
(4, 'México', 'https://images.unsplash.com/photo-1518638150340-f706e86654de?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1518638150340-f706e86654de?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80', 'México es tanto un país de origen, tránsito y destino para migrantes. Su ubicación geográfica lo convierte en un punto clave en las rutas migratorias hacia Estados Unidos. Aquí encontrarás información sobre visas humanitarias, acceso a servicios y programas de protección a migrantes.'),
(5, 'Argentina', 'https://images.unsplash.com/photo-1588696616894-a5c4c11715d7?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1588696616894-a5c4c11715d7?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80', 'Argentina tiene una de las políticas migratorias más abiertas de América Latina. Su Ley de Migraciones reconoce la migración como un derecho humano. Aquí encontrarás información sobre residencias temporarias y permanentes, homologación de estudios y acceso a servicios públicos.');

-- Recursos para España
INSERT INTO resources (title, description, content, category_id, country_id) VALUES
('Guía del proceso de asilo en España', 'Información detallada sobre el proceso de solicitud de asilo y protección internacional.', 'El proceso de solicitud de asilo en España comienza con la manifestación de la voluntad de solicitar protección internacional. Esta solicitud debe realizarse en el plazo de 1 mes desde la entrada en territorio español o desde que se produzcan los hechos que justifiquen el temor de persecución. La solicitud puede presentarse en las siguientes dependencias: Oficina de Asilo y Refugio (OAR), Oficinas de Extranjería, Comisarías de Policía autorizadas o Centros de Internamiento de Extranjeros (CIE). Durante la entrevista, deberás explicar detalladamente los motivos por los que solicitas protección internacional. Tras la solicitud, recibirás un documento que acredita tu condición de solicitante de asilo, el cual te permite permanecer en España hasta que se resuelva tu expediente. Este documento debe renovarse periódicamente. Si tu solicitud es admitida a trámite, se iniciará la fase de instrucción, que puede durar varios meses. Durante este tiempo, a partir de los 6 meses, podrás obtener un permiso de trabajo. Finalmente, se decidirá si se te concede el estatuto de refugiado, la protección subsidiaria o se deniega tu solicitud.', 1, 1),
('Regularización por arraigo social, laboral y familiar', 'Procedimientos para obtener residencia legal a través de diferentes tipos de arraigo.', 'El arraigo social es una autorización de residencia temporal por circunstancias excepcionales que se puede conceder a ciudadanos extranjeros que se encuentren en España y hayan permanecido en el país de forma continuada durante un periodo mínimo de 3 años. Los requisitos principales son: no tener antecedentes penales, contar con un contrato de trabajo firmado por un empleador de al menos 1 año de duración (con salario no inferior al SMI), y tener vínculos familiares con otros extranjeros residentes o presentar un informe de inserción social. El arraigo laboral requiere 2 años de permanencia y demostrar una relación laboral de al menos 6 meses. El arraigo familiar aplica a padres de menores españoles o hijos de españoles de origen. En todos los casos, se debe solicitar cita previa en la Oficina de Extranjería correspondiente y presentar la documentación que acredite el cumplimiento de los requisitos. La resolución suele tardar unos 3 meses. En caso favorable, deberás solicitar la Tarjeta de Identidad de Extranjero (TIE) en un plazo de 1 mes.', 1, 1),
('Homologación de títulos universitarios', 'Guía completa para la homologación y convalidación de títulos académicos extranjeros.', 'La homologación de un título extranjero a un título español es el reconocimiento oficial de la formación superada para la obtención de un título extranjero, como equivalente a la exigida para la obtención de un título español. El proceso se inicia presentando la solicitud a través de la Sede Electrónica del Ministerio de Universidades o presencialmente. La documentación necesaria incluye: formulario de solicitud, copia del documento de identidad, copia compulsada del título que se desea homologar (legalizado y traducido oficialmente), copia compulsada del certificado académico (legalizado y traducido), acreditación del pago de la tasa y, en algunos casos, un programa de las asignaturas cursadas. El plazo de resolución suele ser de 6 a 12 meses. Para profesiones reguladas (médicos, enfermeros, arquitectos, etc.) el proceso puede incluir requisitos adicionales. También existe la opción de la convalidación parcial de estudios, que permite continuar formándose en universidades españolas. Es importante consultar previamente si tu titulación tiene equivalencia en el sistema educativo español.', 4, 1),
('Acceso al sistema sanitario español', 'Información sobre cómo acceder a la sanidad pública y obtener la tarjeta sanitaria.', 'En España, el Sistema Nacional de Salud garantiza la asistencia sanitaria a todos los ciudadanos españoles y a los extranjeros que tengan establecida su residencia en territorio español. Para acceder a los servicios sanitarios es necesario obtener la Tarjeta Sanitaria Individual (TSI). Si eres extranjero con residencia legal, puedes solicitar la TSI presentando en tu centro de salud más cercano tu NIE/TIE, empadronamiento y documento que acredite tu cotización a la Seguridad Social o, en su defecto, un seguro médico. Si eres solicitante de asilo, se te garantiza la asistencia sanitaria desde el momento en que formalizas tu solicitud. Si te encuentras en situación irregular, según el Real Decreto-ley 7/2018, tienes derecho a la atención sanitaria en las mismas condiciones que los españoles, siempre que estés empadronado y no tengas cobertura sanitaria por otra vía. En caso de urgencia por enfermedad grave o accidente, la atención sanitaria está garantizada para cualquier persona, independientemente de su situación administrativa. Para medicamentos recetados, dependiendo de tu situación, podrías pagar un porcentaje del precio según tus ingresos.', 3, 1),
('Sectores con mayor demanda laboral', 'Análisis de los sectores con mayores oportunidades de empleo para migrantes.', 'En España, varios sectores presentan una alta demanda de trabajadores, ofreciendo buenas oportunidades para los migrantes. Entre estos sectores destacan: tecnología (programadores, analistas de datos, especialistas en ciberseguridad), turismo y hostelería (especialmente en temporadas altas en zonas costeras y grandes ciudades), cuidado de personas mayores y servicio doméstico, agricultura (trabajos de temporada en distintas regiones según la época del año), logística y transporte (repartidores, conductores), y construcción. Para acceder a estos empleos, es importante contar con la documentación necesaria para trabajar legalmente. El Servicio Público de Empleo Estatal (SEPE) ofrece orientación laboral y formación. Las agencias de trabajo temporal también son una buena vía para encontrar empleo inicial. Para profesionales cualificados, portales como InfoJobs, LinkedIn o Tecnoempleo son útiles. Las redes de contactos son fundamentales, así como las asociaciones de migrantes que ofrecen orientación laboral. Es recomendable homologar títulos académicos y, si es necesario, realizar cursos de formación complementaria para adaptar tus habilidades al mercado laboral español.', 2, 1),
('Guía de ayudas para el alquiler de vivienda', 'Información sobre subsidios y ayudas disponibles para el acceso a la vivienda.', 'El gobierno español y las comunidades autónomas ofrecen diversas ayudas para facilitar el acceso a la vivienda en alquiler. Entre ellas destacan el Bono Alquiler Joven (para personas de 18 a 35 años, con una ayuda de 250€ mensuales durante 2 años), las ayudas al alquiler para colectivos vulnerables (que pueden cubrir hasta el 50% del alquiler), y las viviendas de protección oficial (VPO) con precios reducidos. Los requisitos generales incluyen: estar legalmente en España, no superar ciertos umbrales de ingresos (variables según la ayuda), destinar la vivienda a residencia habitual, y que el precio del alquiler no supere ciertos límites establecidos. Para solicitarlas, debes informarte en los servicios de vivienda de tu comunidad autónoma o ayuntamiento, ya que son quienes gestionan estas ayudas. La documentación habitual incluye: NIE/TIE, certificado de empadronamiento, contrato de alquiler, declaración de la renta o justificantes de ingresos y, en algunos casos, certificado de vulnerabilidad. También existen organizaciones como Cáritas, Cruz Roja o asociaciones de migrantes que pueden ofrecer ayudas temporales o asesoramiento para acceder a viviendas sociales.', 5, 1);

-- Recursos para Colombia
INSERT INTO resources (title, description, content, category_id, country_id) VALUES
('Permiso Especial de Permanencia (PEP) en Colombia', 'Todo lo que necesitas saber sobre el PEP para migrantes venezolanos.', 'El Permiso Especial de Permanencia (PEP) es un mecanismo de regularización migratoria para los nacionales venezolanos en Colombia, que permite trabajar, estudiar y acceder al sistema de salud, pensión y bancario. Actualmente, este permiso ha sido reemplazado por el Estatuto Temporal de Protección para Migrantes Venezolanos (ETPV), que ofrece un permiso de protección temporal (PPT) con vigencia de 10 años. Para acceder al PPT, debes estar en Colombia antes del 31 de enero de 2021, ya sea de manera regular o irregular, y realizar el proceso de Registro Único de Migrantes Venezolanos a través de la plataforma digital de Migración Colombia. El proceso incluye: pre-registro virtual, registro biométrico presencial y solicitud del PPT. Con este permiso podrás acceder a servicios básicos, trabajar formalmente, abrir cuentas bancarias y afiliarte al sistema de seguridad social. Si ya cuentas con un PEP vigente, este seguirá siendo válido hasta su fecha de vencimiento, momento en el cual deberás transitar al ETPV. Es importante mantener actualizados tus datos en el sistema de Migración Colombia y cumplir con las leyes colombianas para mantener la validez de tu permiso.', 1, 2),
('Sistema de salud colombiano para migrantes', 'Guía para acceder a servicios de salud en Colombia como persona migrante.', 'En Colombia, el sistema de salud se organiza a través del Sistema General de Seguridad Social en Salud (SGSSS), que cuenta con dos regímenes: contributivo (para personas con capacidad de pago) y subsidiado (para personas sin recursos). Los migrantes regulares pueden afiliarse al régimen contributivo si tienen un contrato laboral o realizan aportes como independientes. Si cuentas con el Permiso Especial de Permanencia (PEP) o el Permiso de Protección Temporal (PPT), puedes afiliarte al SGSSS eligiendo una Entidad Promotora de Salud (EPS). Para migrantes en situación vulnerable, existe la posibilidad de aplicar al régimen subsidiado a través del Sistema de Identificación de Potenciales Beneficiarios (Sisbén). Si te encuentras en situación irregular, tienes garantizada la atención de urgencias en cualquier hospital público, aunque para tratamientos continuos necesitarás regularizar tu situación. Las mujeres embarazadas tienen derecho a atención prenatal, parto y posparto independientemente de su estatus migratorio. Para la vacunación, existe el Programa Ampliado de Inmunizaciones (PAI) que es gratuito para todos los niños, incluidos los migrantes. En caso de emergencia, puedes acudir a cualquier hospital o llamar a la línea de emergencias 123.', 3, 2);

-- Recursos para Chile
INSERT INTO resources (title, description, content, category_id, country_id) VALUES
('Acceso al sistema de salud chileno para migrantes', 'Información sobre cómo acceder a la atención médica en Chile.', 'En Chile, los migrantes tienen diferentes opciones para acceder a la atención de salud, dependiendo de su situación migratoria. Aquellos con residencia pueden afiliarse a FONASA (sistema público) o a una ISAPRE (seguro privado). Para afiliarte a FONASA, necesitas tu cédula de identidad y realizar los trámites en cualquier oficina de FONASA o en www.fonasa.cl. FONASA clasifica a sus beneficiarios en tramos según ingresos (A, B, C y D), siendo el tramo A gratuito para personas sin recursos. Los migrantes en situación irregular tienen garantizada la atención de urgencia en cualquier establecimiento de salud. Además, ciertos grupos tienen protección especial independientemente de su estatus migratorio: mujeres embarazadas (control prenatal, parto y hasta 12 meses postparto), niños y niñas hasta los 18 años, y casos de urgencia médica. El Programa de Acceso a la Atención de Salud a Personas Migrantes busca reducir barreras de acceso mediante la implementación de facilitadores interculturales en centros de salud. Para la vacunación, el Plan Nacional de Inmunizaciones es gratuito y universal. En caso de emergencia, puedes acudir a cualquier Servicio de Urgencia de Alta Resolutividad (SAR) o llamar al número de emergencias 131.', 3, 3);

-- Recursos para Argentina
INSERT INTO resources (title, description, content, category_id, country_id) VALUES
('Derechos laborales de los migrantes en Argentina', 'Información sobre el marco legal que protege a los trabajadores migrantes.', 'En Argentina, la Ley de Migraciones garantiza la igualdad de derechos entre nacionales y extranjeros. Los trabajadores migrantes tienen los mismos derechos laborales que los argentinos, incluyendo salario mínimo, jornada laboral, descanso, vacaciones y seguridad social. Para trabajar formalmente necesitas: DNI (Documento Nacional de Identidad) para extranjeros, que se obtiene al iniciar el trámite de residencia, y CUIL (Clave Única de Identificación Laboral), que puedes solicitar en ANSES. Todo trabajador debe ser registrado por su empleador en AFIP, lo que garantiza aportes al sistema de jubilación y obra social (seguro de salud). Si trabajas en relación de dependencia, tienes derecho a un contrato que respete la Ley de Contrato de Trabajo, que incluye protección contra despido injustificado, indemnización, aguinaldo (sueldo anual complementario) y licencias (por enfermedad, maternidad, etc.). En caso de trabajo informal, puedes denunciar al empleador ante el Ministerio de Trabajo o sindicatos. Los trabajadores autónomos deben registrarse como monotributistas, lo que permite facturar legalmente y acceder a jubilación y obra social. Ante discriminación laboral por tu condición de migrante, puedes acudir al INADI (Instituto Nacional contra la Discriminación) para recibir asesoramiento y presentar denuncias.', 2, 5);

-- Eventos
INSERT INTO events (title, description, location, online, date, time, country_id, attendees) VALUES
('Taller de Regularización Migratoria', 'Aprende sobre los procesos de regularización y opciones de permanencia legal en España.', 'Madrid, Centro Cultural (Presencial y Online)', true, NOW() + INTERVAL '15 days', '17:00 - 19:00 CEST', 1, 120),
('Feria de Empleo para Migrantes', 'Conecta con empresas que ofrecen oportunidades laborales para personas migrantes.', 'Santiago, Centro Cultural', false, NOW() + INTERVAL '30 days', '10:00 - 16:00 CLT', 3, 85),
('Charla: Derechos de los Migrantes', 'Informate sobre tus derechos como migrante y los recursos disponibles para defenderlos.', 'Online (Zoom)', true, NOW() + INTERVAL '20 days', '18:00 - 20:00 GMT-3', 5, 65);

-- Contactos de emergencia
INSERT INTO emergency_contacts (name, phone, description, category, country_id) VALUES
('Emergencias', '112', 'Número único europeo de emergencias (policía, ambulancias, bomberos)', 'Emergencias', 1),
('Cruz Roja - Atención al Inmigrante', '900 221 122', 'Asistencia humanitaria, asesoramiento legal y apoyo psicosocial a migrantes', 'Apoyo', 1),
('Línea de Emergencia Migratoria Colombia', '153', 'Atención de emergencias para migrantes venezolanos en Colombia', 'Emergencias', 2),
('SAMU Chile', '131', 'Servicio de atención médica de urgencia en Chile', 'Salud', 3),
('Comisión Mexicana de Ayuda a Refugiados (COMAR)', '+52 55 5209 8800', 'Organismo gubernamental encargado de la protección de refugiados en México', 'Asilo', 4),
('Emergencias Argentina', '911', 'Sistema de atención de urgencias y emergencias', 'Emergencias', 5);

-- Usuario de prueba (contraseña: migrante123)
INSERT INTO users (full_name, username, email, password) VALUES
('Usuario Demostración', 'usuario_demo', 'demo@migraguia.org', '$2b$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy');

-- Publicaciones de ejemplo
INSERT INTO posts (content, user_id, origin_country, destination_country, likes, created_at) VALUES
('Después de 6 meses en España, finalmente conseguí homologar mi título de enfermería. El proceso fue largo pero valió la pena. Recomiendo iniciar los trámites antes de salir del país de origen y apostillar todos los documentos. Si alguien necesita orientación sobre este proceso, ¡estoy aquí para ayudar!', 1, 'Colombia', 'España', 24, NOW() - INTERVAL '2 days'),
('¿Alguien puede darme información sobre el proceso para obtener la visa de responsabilidad democrática en Chile? He escuchado que han cambiado los requisitos recientemente y estoy un poco confundido con la documentación necesaria.', 1, 'Venezuela', 'Chile', 12, NOW() - INTERVAL '5 days');

-- Comentarios de ejemplo
INSERT INTO comments (content, user_id, post_id, created_at) VALUES
('Yo también pasé por ese proceso. Te recomiendo que visites la oficina de extranjería directamente, te ahorrarás mucho tiempo.', 1, 1, NOW() - INTERVAL '1 day'),
('¿Podrías compartir qué documentos exactamente te pidieron? Estoy por iniciar el mismo trámite.', 1, 1, NOW() - INTERVAL '12 hours');
